function plotmap(inM, size_of_marker);
if ~exist('M','var')
   global M
	M = inM;
end

if ~exist('axHndl','var')
   global axHndl
end
if ~exist('figNumber','var')
   global figNumber
end


[xmax, ymax] = size(M);


[x, y] = find(M);


ssize = get(0,'ScreenSize');
figNumber = figure;
set(figNumber,'MenuBar','none','Position',[1 29 ssize(3) ssize(4)-47],'NumberTitle','off',...
   'Name','Simulation Window','RendererMode','manual','Renderer','Painters',...
   'Backingstore','off','tag','map');

plothandle = plot(x,y,'s', ...
   	'Color','g', ...
   	'MarkerFaceColor','g',...
      'MarkerSize',size_of_marker);

set(plothandle,'xdata',x,'ydata',y)

	axis equal
	axHndl=gca;
  	color = get(figNumber,'Color'); 
  
set(axHndl, ...
        'XLim',[0 xmax+1],'YLim',[0 ymax+1], ...
        'XDir','normal','YDir','normal', ...
     	  'Drawmode','fast', ...
        'Visible','on', ...
        'NextPlot','add', ...
        'tag','axes',...
        'XColor',color,...
        'YColor',color);
     
h1 = uicontrol('Parent',figNumber, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
   'Callback','close(gcbf)', ...
	'ListboxTop',0, ...
	'Position',[ssize(3)-round(ssize(3)/3) round(ssize(4)/30) 51.75 21], ...
	'String','Close', ...
	'Tag','cpclose', ...
	'TooltipString','Click to quit');

drawnow;

